# Generated by Django 5.2 on 2025-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_depoimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
