# Generated by Django 5.2 on 2025-05-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projeto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='slug',
        ),
    ]
